<<<<<<< HEAD
name: run_all_tests

on: [push, pull_request, workflow_dispatch]

jobs:
  RunAllTests:
    runs-on: ubuntu-20.04
    container: python:3.9.7
    steps:
      - uses: actions/checkout@v2
      - name: run_all_tests
        run: |
          pip install -r requirements.txt
          pip install -r test-requirements.txt
          python -m pytest
=======
name: run_all_tests

on: [push, pull_request, workflow_dispatch]

jobs:
  RunAllTests:
    runs-on: ubuntu-20.04
    container: python:3.9.7
    steps:
      - uses: actions/checkout@v2
      - name: run_all_tests
        run: |
          pip install -r requirements.txt
          pip install -r test-requirements.txt
          python -m pytest
>>>>>>> fd28223afed0c3f79c6e05b91a56eed9271e7bbd
